//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace NZTA_Contract_Generator {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(0)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class ThisDocument : Microsoft.Office.Tools.Word.DocumentBase {
        
        internal Microsoft.Office.Tools.ActionsPane ActionsPane;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl2;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl3;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl4;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl5;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl6;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl7;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl8;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl9;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl10;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl11;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl12;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl13;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl14;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl15;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl16;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl17;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl18;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl19;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl20;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl21;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl22;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl1;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl23;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl24;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl25;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl26;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl27;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl28;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl29;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl30;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl31;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl32;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl33;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl34;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl35;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl36;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl37;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl38;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl39;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl40;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl41;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl43;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl44;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl45;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl46;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl47;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl48;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl49;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl50;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl51;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl52;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl53;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl54;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl55;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl56;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl57;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl58;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl59;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl60;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl61;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl62;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl63;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl64;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl65;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl66;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl67;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl68;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl69;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl70;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl71;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl72;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl73;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl74;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl75;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl76;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl77;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl78;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl79;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl80;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl81;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl82;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl83;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl84;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl85;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl86;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl87;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl88;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl89;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl90;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl91;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl92;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl93;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl94;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl95;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl96;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl97;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl98;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl99;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl100;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl101;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl102;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl103;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl104;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl105;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl106;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl107;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl108;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl109;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl110;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl111;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl112;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl113;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl114;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl115;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl116;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl117;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl118;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl119;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl120;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl121;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl122;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl123;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl124;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl125;
        
        internal Microsoft.Office.Tools.Word.Bookmark Interactive_Tender_Process;
        
        internal Microsoft.Office.Tools.Word.Bookmark Non_Price_Attributes;
        
        internal Microsoft.Office.Tools.Word.Bookmark Pricing_Options;
        
        internal Microsoft.Office.Tools.Word.Bookmark Tender_Submission_Programme;
        
        internal Microsoft.Office.Tools.Word.Bookmark Contract_Details;
        
        internal Microsoft.Office.Tools.Word.Bookmark Tender_Format;
        
        internal Microsoft.Office.Tools.Word.Bookmark Tender_Evaluation_Procedure;
        
        internal Microsoft.Office.Tools.Word.Bookmark Supplier_Selection_Method;
        
        internal Microsoft.Office.Tools.Word.Bookmark Contract_Pricing;
        
        internal Microsoft.Office.Tools.Word.Bookmark Geotechnical_Testing_Schedule;
        
        internal Microsoft.Office.Tools.Word.Bookmark Additional_Services_Schedule;
        
        internal Microsoft.Office.Tools.Word.Bookmark Personnel_Schedule;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        internal Microsoft.Office.Interop.Word.Application ThisApplication;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public ThisDocument(global::Microsoft.Office.Tools.Word.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "ThisDocument", "ThisDocument") {
            Globals.Factory = factory;
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            this.ThisApplication = this.GetHostItem<Microsoft.Office.Interop.Word.Application>(typeof(Microsoft.Office.Interop.Word.Application), "Application");
            Globals.ThisDocument = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
            this.ActionsPane.BeginInit();
            this.richTextContentControl2.BeginInit();
            this.richTextContentControl3.BeginInit();
            this.richTextContentControl4.BeginInit();
            this.richTextContentControl5.BeginInit();
            this.richTextContentControl6.BeginInit();
            this.richTextContentControl7.BeginInit();
            this.richTextContentControl8.BeginInit();
            this.richTextContentControl9.BeginInit();
            this.richTextContentControl10.BeginInit();
            this.richTextContentControl11.BeginInit();
            this.richTextContentControl12.BeginInit();
            this.richTextContentControl13.BeginInit();
            this.richTextContentControl14.BeginInit();
            this.richTextContentControl15.BeginInit();
            this.richTextContentControl16.BeginInit();
            this.richTextContentControl17.BeginInit();
            this.richTextContentControl18.BeginInit();
            this.richTextContentControl19.BeginInit();
            this.richTextContentControl20.BeginInit();
            this.richTextContentControl21.BeginInit();
            this.richTextContentControl22.BeginInit();
            this.richTextContentControl1.BeginInit();
            this.richTextContentControl23.BeginInit();
            this.richTextContentControl24.BeginInit();
            this.richTextContentControl25.BeginInit();
            this.richTextContentControl26.BeginInit();
            this.richTextContentControl27.BeginInit();
            this.richTextContentControl28.BeginInit();
            this.richTextContentControl29.BeginInit();
            this.richTextContentControl30.BeginInit();
            this.richTextContentControl31.BeginInit();
            this.richTextContentControl32.BeginInit();
            this.richTextContentControl33.BeginInit();
            this.richTextContentControl34.BeginInit();
            this.richTextContentControl35.BeginInit();
            this.richTextContentControl36.BeginInit();
            this.richTextContentControl37.BeginInit();
            this.richTextContentControl38.BeginInit();
            this.richTextContentControl39.BeginInit();
            this.richTextContentControl40.BeginInit();
            this.richTextContentControl41.BeginInit();
            this.richTextContentControl43.BeginInit();
            this.richTextContentControl44.BeginInit();
            this.richTextContentControl45.BeginInit();
            this.richTextContentControl46.BeginInit();
            this.richTextContentControl47.BeginInit();
            this.richTextContentControl48.BeginInit();
            this.richTextContentControl49.BeginInit();
            this.richTextContentControl50.BeginInit();
            this.richTextContentControl51.BeginInit();
            this.richTextContentControl52.BeginInit();
            this.richTextContentControl53.BeginInit();
            this.richTextContentControl54.BeginInit();
            this.richTextContentControl55.BeginInit();
            this.richTextContentControl56.BeginInit();
            this.richTextContentControl57.BeginInit();
            this.richTextContentControl58.BeginInit();
            this.richTextContentControl59.BeginInit();
            this.richTextContentControl60.BeginInit();
            this.richTextContentControl61.BeginInit();
            this.richTextContentControl62.BeginInit();
            this.richTextContentControl63.BeginInit();
            this.richTextContentControl64.BeginInit();
            this.richTextContentControl65.BeginInit();
            this.richTextContentControl66.BeginInit();
            this.richTextContentControl67.BeginInit();
            this.richTextContentControl68.BeginInit();
            this.richTextContentControl69.BeginInit();
            this.richTextContentControl70.BeginInit();
            this.richTextContentControl71.BeginInit();
            this.richTextContentControl72.BeginInit();
            this.richTextContentControl73.BeginInit();
            this.richTextContentControl74.BeginInit();
            this.richTextContentControl75.BeginInit();
            this.richTextContentControl76.BeginInit();
            this.richTextContentControl77.BeginInit();
            this.richTextContentControl78.BeginInit();
            this.richTextContentControl79.BeginInit();
            this.richTextContentControl80.BeginInit();
            this.richTextContentControl81.BeginInit();
            this.richTextContentControl82.BeginInit();
            this.richTextContentControl83.BeginInit();
            this.richTextContentControl84.BeginInit();
            this.richTextContentControl85.BeginInit();
            this.richTextContentControl86.BeginInit();
            this.richTextContentControl87.BeginInit();
            this.richTextContentControl88.BeginInit();
            this.richTextContentControl89.BeginInit();
            this.richTextContentControl90.BeginInit();
            this.richTextContentControl91.BeginInit();
            this.richTextContentControl92.BeginInit();
            this.richTextContentControl93.BeginInit();
            this.richTextContentControl94.BeginInit();
            this.richTextContentControl95.BeginInit();
            this.richTextContentControl96.BeginInit();
            this.richTextContentControl97.BeginInit();
            this.richTextContentControl98.BeginInit();
            this.richTextContentControl99.BeginInit();
            this.richTextContentControl100.BeginInit();
            this.richTextContentControl101.BeginInit();
            this.richTextContentControl102.BeginInit();
            this.richTextContentControl103.BeginInit();
            this.richTextContentControl104.BeginInit();
            this.richTextContentControl105.BeginInit();
            this.richTextContentControl106.BeginInit();
            this.richTextContentControl107.BeginInit();
            this.richTextContentControl108.BeginInit();
            this.richTextContentControl109.BeginInit();
            this.richTextContentControl110.BeginInit();
            this.richTextContentControl111.BeginInit();
            this.richTextContentControl112.BeginInit();
            this.richTextContentControl113.BeginInit();
            this.richTextContentControl114.BeginInit();
            this.richTextContentControl115.BeginInit();
            this.richTextContentControl116.BeginInit();
            this.richTextContentControl117.BeginInit();
            this.richTextContentControl118.BeginInit();
            this.richTextContentControl119.BeginInit();
            this.richTextContentControl120.BeginInit();
            this.richTextContentControl121.BeginInit();
            this.richTextContentControl122.BeginInit();
            this.richTextContentControl123.BeginInit();
            this.richTextContentControl124.BeginInit();
            this.richTextContentControl125.BeginInit();
            this.Interactive_Tender_Process.BeginInit();
            this.Non_Price_Attributes.BeginInit();
            this.Pricing_Options.BeginInit();
            this.Tender_Submission_Programme.BeginInit();
            this.Contract_Details.BeginInit();
            this.Tender_Format.BeginInit();
            this.Tender_Evaluation_Procedure.BeginInit();
            this.Supplier_Selection_Method.BeginInit();
            this.Contract_Pricing.BeginInit();
            this.Geotechnical_Testing_Schedule.BeginInit();
            this.Additional_Services_Schedule.BeginInit();
            this.Personnel_Schedule.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.Personnel_Schedule.EndInit();
            this.Additional_Services_Schedule.EndInit();
            this.Geotechnical_Testing_Schedule.EndInit();
            this.Contract_Pricing.EndInit();
            this.Supplier_Selection_Method.EndInit();
            this.Tender_Evaluation_Procedure.EndInit();
            this.Tender_Format.EndInit();
            this.Contract_Details.EndInit();
            this.Tender_Submission_Programme.EndInit();
            this.Pricing_Options.EndInit();
            this.Non_Price_Attributes.EndInit();
            this.Interactive_Tender_Process.EndInit();
            this.richTextContentControl125.EndInit();
            this.richTextContentControl124.EndInit();
            this.richTextContentControl123.EndInit();
            this.richTextContentControl122.EndInit();
            this.richTextContentControl121.EndInit();
            this.richTextContentControl120.EndInit();
            this.richTextContentControl119.EndInit();
            this.richTextContentControl118.EndInit();
            this.richTextContentControl117.EndInit();
            this.richTextContentControl116.EndInit();
            this.richTextContentControl115.EndInit();
            this.richTextContentControl114.EndInit();
            this.richTextContentControl113.EndInit();
            this.richTextContentControl112.EndInit();
            this.richTextContentControl111.EndInit();
            this.richTextContentControl110.EndInit();
            this.richTextContentControl109.EndInit();
            this.richTextContentControl108.EndInit();
            this.richTextContentControl107.EndInit();
            this.richTextContentControl106.EndInit();
            this.richTextContentControl105.EndInit();
            this.richTextContentControl104.EndInit();
            this.richTextContentControl103.EndInit();
            this.richTextContentControl102.EndInit();
            this.richTextContentControl101.EndInit();
            this.richTextContentControl100.EndInit();
            this.richTextContentControl99.EndInit();
            this.richTextContentControl98.EndInit();
            this.richTextContentControl97.EndInit();
            this.richTextContentControl96.EndInit();
            this.richTextContentControl95.EndInit();
            this.richTextContentControl94.EndInit();
            this.richTextContentControl93.EndInit();
            this.richTextContentControl92.EndInit();
            this.richTextContentControl91.EndInit();
            this.richTextContentControl90.EndInit();
            this.richTextContentControl89.EndInit();
            this.richTextContentControl88.EndInit();
            this.richTextContentControl87.EndInit();
            this.richTextContentControl86.EndInit();
            this.richTextContentControl85.EndInit();
            this.richTextContentControl84.EndInit();
            this.richTextContentControl83.EndInit();
            this.richTextContentControl82.EndInit();
            this.richTextContentControl81.EndInit();
            this.richTextContentControl80.EndInit();
            this.richTextContentControl79.EndInit();
            this.richTextContentControl78.EndInit();
            this.richTextContentControl77.EndInit();
            this.richTextContentControl76.EndInit();
            this.richTextContentControl75.EndInit();
            this.richTextContentControl74.EndInit();
            this.richTextContentControl73.EndInit();
            this.richTextContentControl72.EndInit();
            this.richTextContentControl71.EndInit();
            this.richTextContentControl70.EndInit();
            this.richTextContentControl69.EndInit();
            this.richTextContentControl68.EndInit();
            this.richTextContentControl67.EndInit();
            this.richTextContentControl66.EndInit();
            this.richTextContentControl65.EndInit();
            this.richTextContentControl64.EndInit();
            this.richTextContentControl63.EndInit();
            this.richTextContentControl62.EndInit();
            this.richTextContentControl61.EndInit();
            this.richTextContentControl60.EndInit();
            this.richTextContentControl59.EndInit();
            this.richTextContentControl58.EndInit();
            this.richTextContentControl57.EndInit();
            this.richTextContentControl56.EndInit();
            this.richTextContentControl55.EndInit();
            this.richTextContentControl54.EndInit();
            this.richTextContentControl53.EndInit();
            this.richTextContentControl52.EndInit();
            this.richTextContentControl51.EndInit();
            this.richTextContentControl50.EndInit();
            this.richTextContentControl49.EndInit();
            this.richTextContentControl48.EndInit();
            this.richTextContentControl47.EndInit();
            this.richTextContentControl46.EndInit();
            this.richTextContentControl45.EndInit();
            this.richTextContentControl44.EndInit();
            this.richTextContentControl43.EndInit();
            this.richTextContentControl41.EndInit();
            this.richTextContentControl40.EndInit();
            this.richTextContentControl39.EndInit();
            this.richTextContentControl38.EndInit();
            this.richTextContentControl37.EndInit();
            this.richTextContentControl36.EndInit();
            this.richTextContentControl35.EndInit();
            this.richTextContentControl34.EndInit();
            this.richTextContentControl33.EndInit();
            this.richTextContentControl32.EndInit();
            this.richTextContentControl31.EndInit();
            this.richTextContentControl30.EndInit();
            this.richTextContentControl29.EndInit();
            this.richTextContentControl28.EndInit();
            this.richTextContentControl27.EndInit();
            this.richTextContentControl26.EndInit();
            this.richTextContentControl25.EndInit();
            this.richTextContentControl24.EndInit();
            this.richTextContentControl23.EndInit();
            this.richTextContentControl1.EndInit();
            this.richTextContentControl22.EndInit();
            this.richTextContentControl21.EndInit();
            this.richTextContentControl20.EndInit();
            this.richTextContentControl19.EndInit();
            this.richTextContentControl18.EndInit();
            this.richTextContentControl17.EndInit();
            this.richTextContentControl16.EndInit();
            this.richTextContentControl15.EndInit();
            this.richTextContentControl14.EndInit();
            this.richTextContentControl13.EndInit();
            this.richTextContentControl12.EndInit();
            this.richTextContentControl11.EndInit();
            this.richTextContentControl10.EndInit();
            this.richTextContentControl9.EndInit();
            this.richTextContentControl8.EndInit();
            this.richTextContentControl7.EndInit();
            this.richTextContentControl6.EndInit();
            this.richTextContentControl5.EndInit();
            this.richTextContentControl4.EndInit();
            this.richTextContentControl3.EndInit();
            this.richTextContentControl2.EndInit();
            this.ActionsPane.EndInit();
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.ActionsPane = Globals.Factory.CreateActionsPane(null, null, "ActionsPane", "ActionsPane", this);
            this.richTextContentControl2 = Globals.Factory.CreateRichTextContentControl(null, null, "2995438561", "richTextContentControl2", this);
            this.richTextContentControl3 = Globals.Factory.CreateRichTextContentControl(null, null, "3011478966", "richTextContentControl3", this);
            this.richTextContentControl4 = Globals.Factory.CreateRichTextContentControl(null, null, "3964212976", "richTextContentControl4", this);
            this.richTextContentControl5 = Globals.Factory.CreateRichTextContentControl(null, null, "1492531140", "richTextContentControl5", this);
            this.richTextContentControl6 = Globals.Factory.CreateRichTextContentControl(null, null, "48886945", "richTextContentControl6", this);
            this.richTextContentControl7 = Globals.Factory.CreateRichTextContentControl(null, null, "872501667", "richTextContentControl7", this);
            this.richTextContentControl8 = Globals.Factory.CreateRichTextContentControl(null, null, "2438016426", "richTextContentControl8", this);
            this.richTextContentControl9 = Globals.Factory.CreateRichTextContentControl(null, null, "321312835", "richTextContentControl9", this);
            this.richTextContentControl10 = Globals.Factory.CreateRichTextContentControl(null, null, "2628732258", "richTextContentControl10", this);
            this.richTextContentControl11 = Globals.Factory.CreateRichTextContentControl(null, null, "725884906", "richTextContentControl11", this);
            this.richTextContentControl12 = Globals.Factory.CreateRichTextContentControl(null, null, "4137966592", "richTextContentControl12", this);
            this.richTextContentControl13 = Globals.Factory.CreateRichTextContentControl(null, null, "520352158", "richTextContentControl13", this);
            this.richTextContentControl14 = Globals.Factory.CreateRichTextContentControl(null, null, "3806717593", "richTextContentControl14", this);
            this.richTextContentControl15 = Globals.Factory.CreateRichTextContentControl(null, null, "4203496865", "richTextContentControl15", this);
            this.richTextContentControl16 = Globals.Factory.CreateRichTextContentControl(null, null, "2950499455", "richTextContentControl16", this);
            this.richTextContentControl17 = Globals.Factory.CreateRichTextContentControl(null, null, "4117237585", "richTextContentControl17", this);
            this.richTextContentControl18 = Globals.Factory.CreateRichTextContentControl(null, null, "3173909173", "richTextContentControl18", this);
            this.richTextContentControl19 = Globals.Factory.CreateRichTextContentControl(null, null, "860010837", "richTextContentControl19", this);
            this.richTextContentControl20 = Globals.Factory.CreateRichTextContentControl(null, null, "1275054114", "richTextContentControl20", this);
            this.richTextContentControl21 = Globals.Factory.CreateRichTextContentControl(null, null, "1152408033", "richTextContentControl21", this);
            this.richTextContentControl22 = Globals.Factory.CreateRichTextContentControl(null, null, "2809499199", "richTextContentControl22", this);
            this.richTextContentControl1 = Globals.Factory.CreateRichTextContentControl(null, null, "1603068122", "richTextContentControl1", this);
            this.richTextContentControl23 = Globals.Factory.CreateRichTextContentControl(null, null, "1668204497", "richTextContentControl23", this);
            this.richTextContentControl24 = Globals.Factory.CreateRichTextContentControl(null, null, "2246138551", "richTextContentControl24", this);
            this.richTextContentControl25 = Globals.Factory.CreateRichTextContentControl(null, null, "3929831446", "richTextContentControl25", this);
            this.richTextContentControl26 = Globals.Factory.CreateRichTextContentControl(null, null, "1162047053", "richTextContentControl26", this);
            this.richTextContentControl27 = Globals.Factory.CreateRichTextContentControl(null, null, "447735765", "richTextContentControl27", this);
            this.richTextContentControl28 = Globals.Factory.CreateRichTextContentControl(null, null, "941338972", "richTextContentControl28", this);
            this.richTextContentControl29 = Globals.Factory.CreateRichTextContentControl(null, null, "1839502725", "richTextContentControl29", this);
            this.richTextContentControl30 = Globals.Factory.CreateRichTextContentControl(null, null, "1673536519", "richTextContentControl30", this);
            this.richTextContentControl31 = Globals.Factory.CreateRichTextContentControl(null, null, "1556360508", "richTextContentControl31", this);
            this.richTextContentControl32 = Globals.Factory.CreateRichTextContentControl(null, null, "2759396735", "richTextContentControl32", this);
            this.richTextContentControl33 = Globals.Factory.CreateRichTextContentControl(null, null, "393324230", "richTextContentControl33", this);
            this.richTextContentControl34 = Globals.Factory.CreateRichTextContentControl(null, null, "1695653966", "richTextContentControl34", this);
            this.richTextContentControl35 = Globals.Factory.CreateRichTextContentControl(null, null, "662434785", "richTextContentControl35", this);
            this.richTextContentControl36 = Globals.Factory.CreateRichTextContentControl(null, null, "1792243549", "richTextContentControl36", this);
            this.richTextContentControl37 = Globals.Factory.CreateRichTextContentControl(null, null, "2271507081", "richTextContentControl37", this);
            this.richTextContentControl38 = Globals.Factory.CreateRichTextContentControl(null, null, "3000989983", "richTextContentControl38", this);
            this.richTextContentControl39 = Globals.Factory.CreateRichTextContentControl(null, null, "869421511", "richTextContentControl39", this);
            this.richTextContentControl40 = Globals.Factory.CreateRichTextContentControl(null, null, "460859104", "richTextContentControl40", this);
            this.richTextContentControl41 = Globals.Factory.CreateRichTextContentControl(null, null, "74411214", "richTextContentControl41", this);
            this.richTextContentControl43 = Globals.Factory.CreateRichTextContentControl(null, null, "4135955664", "richTextContentControl43", this);
            this.richTextContentControl44 = Globals.Factory.CreateRichTextContentControl(null, null, "3899370984", "richTextContentControl44", this);
            this.richTextContentControl45 = Globals.Factory.CreateRichTextContentControl(null, null, "312373938", "richTextContentControl45", this);
            this.richTextContentControl46 = Globals.Factory.CreateRichTextContentControl(null, null, "1661040138", "richTextContentControl46", this);
            this.richTextContentControl47 = Globals.Factory.CreateRichTextContentControl(null, null, "3172821666", "richTextContentControl47", this);
            this.richTextContentControl48 = Globals.Factory.CreateRichTextContentControl(null, null, "46739209", "richTextContentControl48", this);
            this.richTextContentControl49 = Globals.Factory.CreateRichTextContentControl(null, null, "799043528", "richTextContentControl49", this);
            this.richTextContentControl50 = Globals.Factory.CreateRichTextContentControl(null, null, "1227035432", "richTextContentControl50", this);
            this.richTextContentControl51 = Globals.Factory.CreateRichTextContentControl(null, null, "795332043", "richTextContentControl51", this);
            this.richTextContentControl52 = Globals.Factory.CreateRichTextContentControl(null, null, "2029049825", "richTextContentControl52", this);
            this.richTextContentControl53 = Globals.Factory.CreateRichTextContentControl(null, null, "131995785", "richTextContentControl53", this);
            this.richTextContentControl54 = Globals.Factory.CreateRichTextContentControl(null, null, "2451507104", "richTextContentControl54", this);
            this.richTextContentControl55 = Globals.Factory.CreateRichTextContentControl(null, null, "3877098858", "richTextContentControl55", this);
            this.richTextContentControl56 = Globals.Factory.CreateRichTextContentControl(null, null, "1560362615", "richTextContentControl56", this);
            this.richTextContentControl57 = Globals.Factory.CreateRichTextContentControl(null, null, "272366006", "richTextContentControl57", this);
            this.richTextContentControl58 = Globals.Factory.CreateRichTextContentControl(null, null, "4159626105", "richTextContentControl58", this);
            this.richTextContentControl59 = Globals.Factory.CreateRichTextContentControl(null, null, "341986538", "richTextContentControl59", this);
            this.richTextContentControl60 = Globals.Factory.CreateRichTextContentControl(null, null, "69089062", "richTextContentControl60", this);
            this.richTextContentControl61 = Globals.Factory.CreateRichTextContentControl(null, null, "109629875", "richTextContentControl61", this);
            this.richTextContentControl62 = Globals.Factory.CreateRichTextContentControl(null, null, "657958454", "richTextContentControl62", this);
            this.richTextContentControl63 = Globals.Factory.CreateRichTextContentControl(null, null, "3563351903", "richTextContentControl63", this);
            this.richTextContentControl64 = Globals.Factory.CreateRichTextContentControl(null, null, "3909930918", "richTextContentControl64", this);
            this.richTextContentControl65 = Globals.Factory.CreateRichTextContentControl(null, null, "2141539433", "richTextContentControl65", this);
            this.richTextContentControl66 = Globals.Factory.CreateRichTextContentControl(null, null, "1853837190", "richTextContentControl66", this);
            this.richTextContentControl67 = Globals.Factory.CreateRichTextContentControl(null, null, "1823993579", "richTextContentControl67", this);
            this.richTextContentControl68 = Globals.Factory.CreateRichTextContentControl(null, null, "418218952", "richTextContentControl68", this);
            this.richTextContentControl69 = Globals.Factory.CreateRichTextContentControl(null, null, "3906922201", "richTextContentControl69", this);
            this.richTextContentControl70 = Globals.Factory.CreateRichTextContentControl(null, null, "1328790965", "richTextContentControl70", this);
            this.richTextContentControl71 = Globals.Factory.CreateRichTextContentControl(null, null, "850064440", "richTextContentControl71", this);
            this.richTextContentControl72 = Globals.Factory.CreateRichTextContentControl(null, null, "136778827", "richTextContentControl72", this);
            this.richTextContentControl73 = Globals.Factory.CreateRichTextContentControl(null, null, "3287983803", "richTextContentControl73", this);
            this.richTextContentControl74 = Globals.Factory.CreateRichTextContentControl(null, null, "3822673428", "richTextContentControl74", this);
            this.richTextContentControl75 = Globals.Factory.CreateRichTextContentControl(null, null, "3385651841", "richTextContentControl75", this);
            this.richTextContentControl76 = Globals.Factory.CreateRichTextContentControl(null, null, "3670354976", "richTextContentControl76", this);
            this.richTextContentControl77 = Globals.Factory.CreateRichTextContentControl(null, null, "516509744", "richTextContentControl77", this);
            this.richTextContentControl78 = Globals.Factory.CreateRichTextContentControl(null, null, "2764631749", "richTextContentControl78", this);
            this.richTextContentControl79 = Globals.Factory.CreateRichTextContentControl(null, null, "1383983299", "richTextContentControl79", this);
            this.richTextContentControl80 = Globals.Factory.CreateRichTextContentControl(null, null, "4059557857", "richTextContentControl80", this);
            this.richTextContentControl81 = Globals.Factory.CreateRichTextContentControl(null, null, "4097488767", "richTextContentControl81", this);
            this.richTextContentControl82 = Globals.Factory.CreateRichTextContentControl(null, null, "1366956474", "richTextContentControl82", this);
            this.richTextContentControl83 = Globals.Factory.CreateRichTextContentControl(null, null, "840744964", "richTextContentControl83", this);
            this.richTextContentControl84 = Globals.Factory.CreateRichTextContentControl(null, null, "2173434664", "richTextContentControl84", this);
            this.richTextContentControl85 = Globals.Factory.CreateRichTextContentControl(null, null, "1312837409", "richTextContentControl85", this);
            this.richTextContentControl86 = Globals.Factory.CreateRichTextContentControl(null, null, "1401248721", "richTextContentControl86", this);
            this.richTextContentControl87 = Globals.Factory.CreateRichTextContentControl(null, null, "3945868115", "richTextContentControl87", this);
            this.richTextContentControl88 = Globals.Factory.CreateRichTextContentControl(null, null, "251789873", "richTextContentControl88", this);
            this.richTextContentControl89 = Globals.Factory.CreateRichTextContentControl(null, null, "3480546701", "richTextContentControl89", this);
            this.richTextContentControl90 = Globals.Factory.CreateRichTextContentControl(null, null, "3054182277", "richTextContentControl90", this);
            this.richTextContentControl91 = Globals.Factory.CreateRichTextContentControl(null, null, "2622796836", "richTextContentControl91", this);
            this.richTextContentControl92 = Globals.Factory.CreateRichTextContentControl(null, null, "632604631", "richTextContentControl92", this);
            this.richTextContentControl93 = Globals.Factory.CreateRichTextContentControl(null, null, "4213202597", "richTextContentControl93", this);
            this.richTextContentControl94 = Globals.Factory.CreateRichTextContentControl(null, null, "699198431", "richTextContentControl94", this);
            this.richTextContentControl95 = Globals.Factory.CreateRichTextContentControl(null, null, "1055048864", "richTextContentControl95", this);
            this.richTextContentControl96 = Globals.Factory.CreateRichTextContentControl(null, null, "3649845009", "richTextContentControl96", this);
            this.richTextContentControl97 = Globals.Factory.CreateRichTextContentControl(null, null, "3777121332", "richTextContentControl97", this);
            this.richTextContentControl98 = Globals.Factory.CreateRichTextContentControl(null, null, "2892361494", "richTextContentControl98", this);
            this.richTextContentControl99 = Globals.Factory.CreateRichTextContentControl(null, null, "2356379687", "richTextContentControl99", this);
            this.richTextContentControl100 = Globals.Factory.CreateRichTextContentControl(null, null, "2456515144", "richTextContentControl100", this);
            this.richTextContentControl101 = Globals.Factory.CreateRichTextContentControl(null, null, "2083798432", "richTextContentControl101", this);
            this.richTextContentControl102 = Globals.Factory.CreateRichTextContentControl(null, null, "1699817685", "richTextContentControl102", this);
            this.richTextContentControl103 = Globals.Factory.CreateRichTextContentControl(null, null, "3426907381", "richTextContentControl103", this);
            this.richTextContentControl104 = Globals.Factory.CreateRichTextContentControl(null, null, "1162504390", "richTextContentControl104", this);
            this.richTextContentControl105 = Globals.Factory.CreateRichTextContentControl(null, null, "1672835320", "richTextContentControl105", this);
            this.richTextContentControl106 = Globals.Factory.CreateRichTextContentControl(null, null, "946731594", "richTextContentControl106", this);
            this.richTextContentControl107 = Globals.Factory.CreateRichTextContentControl(null, null, "1442416395", "richTextContentControl107", this);
            this.richTextContentControl108 = Globals.Factory.CreateRichTextContentControl(null, null, "47584081", "richTextContentControl108", this);
            this.richTextContentControl109 = Globals.Factory.CreateRichTextContentControl(null, null, "1338034255", "richTextContentControl109", this);
            this.richTextContentControl110 = Globals.Factory.CreateRichTextContentControl(null, null, "4137893328", "richTextContentControl110", this);
            this.richTextContentControl111 = Globals.Factory.CreateRichTextContentControl(null, null, "2940018876", "richTextContentControl111", this);
            this.richTextContentControl112 = Globals.Factory.CreateRichTextContentControl(null, null, "307831456", "richTextContentControl112", this);
            this.richTextContentControl113 = Globals.Factory.CreateRichTextContentControl(null, null, "2922898581", "richTextContentControl113", this);
            this.richTextContentControl114 = Globals.Factory.CreateRichTextContentControl(null, null, "2223713893", "richTextContentControl114", this);
            this.richTextContentControl115 = Globals.Factory.CreateRichTextContentControl(null, null, "900637968", "richTextContentControl115", this);
            this.richTextContentControl116 = Globals.Factory.CreateRichTextContentControl(null, null, "3322219477", "richTextContentControl116", this);
            this.richTextContentControl117 = Globals.Factory.CreateRichTextContentControl(null, null, "773056331", "richTextContentControl117", this);
            this.richTextContentControl118 = Globals.Factory.CreateRichTextContentControl(null, null, "4248128866", "richTextContentControl118", this);
            this.richTextContentControl119 = Globals.Factory.CreateRichTextContentControl(null, null, "1632279992", "richTextContentControl119", this);
            this.richTextContentControl120 = Globals.Factory.CreateRichTextContentControl(null, null, "1181942687", "richTextContentControl120", this);
            this.richTextContentControl121 = Globals.Factory.CreateRichTextContentControl(null, null, "750698887", "richTextContentControl121", this);
            this.richTextContentControl122 = Globals.Factory.CreateRichTextContentControl(null, null, "2929223368", "richTextContentControl122", this);
            this.richTextContentControl123 = Globals.Factory.CreateRichTextContentControl(null, null, "1585649752", "richTextContentControl123", this);
            this.richTextContentControl124 = Globals.Factory.CreateRichTextContentControl(null, null, "379295691", "richTextContentControl124", this);
            this.richTextContentControl125 = Globals.Factory.CreateRichTextContentControl(null, null, "2476395455", "richTextContentControl125", this);
            this.Interactive_Tender_Process = Globals.Factory.CreateBookmark(null, null, "Interactive_Tender_Process", "Interactive_Tender_Process", this);
            this.Non_Price_Attributes = Globals.Factory.CreateBookmark(null, null, "Non_Price_Attributes", "Non_Price_Attributes", this);
            this.Pricing_Options = Globals.Factory.CreateBookmark(null, null, "Pricing_Options", "Pricing_Options", this);
            this.Tender_Submission_Programme = Globals.Factory.CreateBookmark(null, null, "Tender_Submission_Programme", "Tender_Submission_Programme", this);
            this.Contract_Details = Globals.Factory.CreateBookmark(null, null, "Contract_Details", "Contract_Details", this);
            this.Tender_Format = Globals.Factory.CreateBookmark(null, null, "Tender_Format", "Tender_Format", this);
            this.Tender_Evaluation_Procedure = Globals.Factory.CreateBookmark(null, null, "Tender_Evaluation_Procedure", "Tender_Evaluation_Procedure", this);
            this.Supplier_Selection_Method = Globals.Factory.CreateBookmark(null, null, "Supplier_Selection_Method", "Supplier_Selection_Method", this);
            this.Contract_Pricing = Globals.Factory.CreateBookmark(null, null, "Contract_Pricing", "Contract_Pricing", this);
            this.Geotechnical_Testing_Schedule = Globals.Factory.CreateBookmark(null, null, "Geotechnical_Testing_Schedule", "Geotechnical_Testing_Schedule", this);
            this.Additional_Services_Schedule = Globals.Factory.CreateBookmark(null, null, "Additional_Services_Schedule", "Additional_Services_Schedule", this);
            this.Personnel_Schedule = Globals.Factory.CreateBookmark(null, null, "Personnel_Schedule", "Personnel_Schedule", this);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            // 
            // ActionsPane
            // 
            this.ActionsPane.AutoSize = false;
            this.ActionsPane.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            // 
            // richTextContentControl2
            // 
            this.richTextContentControl2.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl3
            // 
            this.richTextContentControl3.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl4
            // 
            this.richTextContentControl4.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl5
            // 
            this.richTextContentControl5.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl6
            // 
            this.richTextContentControl6.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl7
            // 
            this.richTextContentControl7.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl8
            // 
            this.richTextContentControl8.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl9
            // 
            this.richTextContentControl9.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl10
            // 
            this.richTextContentControl10.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl11
            // 
            this.richTextContentControl11.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl12
            // 
            this.richTextContentControl12.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl13
            // 
            this.richTextContentControl13.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl14
            // 
            this.richTextContentControl14.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl15
            // 
            this.richTextContentControl15.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl16
            // 
            this.richTextContentControl16.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl17
            // 
            this.richTextContentControl17.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl18
            // 
            this.richTextContentControl18.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl19
            // 
            this.richTextContentControl19.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl20
            // 
            this.richTextContentControl20.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl21
            // 
            this.richTextContentControl21.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl22
            // 
            this.richTextContentControl22.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl1
            // 
            this.richTextContentControl1.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl23
            // 
            this.richTextContentControl23.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl24
            // 
            this.richTextContentControl24.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl25
            // 
            this.richTextContentControl25.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl26
            // 
            this.richTextContentControl26.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl27
            // 
            this.richTextContentControl27.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl28
            // 
            this.richTextContentControl28.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl29
            // 
            this.richTextContentControl29.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl30
            // 
            this.richTextContentControl30.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl31
            // 
            this.richTextContentControl31.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl32
            // 
            this.richTextContentControl32.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl33
            // 
            this.richTextContentControl33.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl34
            // 
            this.richTextContentControl34.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl35
            // 
            this.richTextContentControl35.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl36
            // 
            this.richTextContentControl36.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl37
            // 
            this.richTextContentControl37.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl38
            // 
            this.richTextContentControl38.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl39
            // 
            this.richTextContentControl39.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl40
            // 
            this.richTextContentControl40.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl41
            // 
            this.richTextContentControl41.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl43
            // 
            this.richTextContentControl43.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl44
            // 
            this.richTextContentControl44.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl45
            // 
            this.richTextContentControl45.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl46
            // 
            this.richTextContentControl46.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl47
            // 
            this.richTextContentControl47.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl48
            // 
            this.richTextContentControl48.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl49
            // 
            this.richTextContentControl49.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl50
            // 
            this.richTextContentControl50.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl51
            // 
            this.richTextContentControl51.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl52
            // 
            this.richTextContentControl52.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl53
            // 
            this.richTextContentControl53.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl54
            // 
            this.richTextContentControl54.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl55
            // 
            this.richTextContentControl55.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl56
            // 
            this.richTextContentControl56.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl57
            // 
            this.richTextContentControl57.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl58
            // 
            this.richTextContentControl58.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl59
            // 
            this.richTextContentControl59.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl60
            // 
            this.richTextContentControl60.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl61
            // 
            this.richTextContentControl61.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl62
            // 
            this.richTextContentControl62.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl63
            // 
            this.richTextContentControl63.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl64
            // 
            this.richTextContentControl64.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl65
            // 
            this.richTextContentControl65.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl66
            // 
            this.richTextContentControl66.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl67
            // 
            this.richTextContentControl67.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl68
            // 
            this.richTextContentControl68.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl69
            // 
            this.richTextContentControl69.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl70
            // 
            this.richTextContentControl70.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl71
            // 
            this.richTextContentControl71.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl72
            // 
            this.richTextContentControl72.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl73
            // 
            this.richTextContentControl73.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl74
            // 
            this.richTextContentControl74.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl75
            // 
            this.richTextContentControl75.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl76
            // 
            this.richTextContentControl76.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl77
            // 
            this.richTextContentControl77.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl78
            // 
            this.richTextContentControl78.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl79
            // 
            this.richTextContentControl79.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl80
            // 
            this.richTextContentControl80.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl81
            // 
            this.richTextContentControl81.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl82
            // 
            this.richTextContentControl82.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl83
            // 
            this.richTextContentControl83.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl84
            // 
            this.richTextContentControl84.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl85
            // 
            this.richTextContentControl85.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl86
            // 
            this.richTextContentControl86.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl87
            // 
            this.richTextContentControl87.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl88
            // 
            this.richTextContentControl88.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl89
            // 
            this.richTextContentControl89.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl90
            // 
            this.richTextContentControl90.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl91
            // 
            this.richTextContentControl91.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl92
            // 
            this.richTextContentControl92.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl93
            // 
            this.richTextContentControl93.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl94
            // 
            this.richTextContentControl94.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl95
            // 
            this.richTextContentControl95.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl96
            // 
            this.richTextContentControl96.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl97
            // 
            this.richTextContentControl97.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl98
            // 
            this.richTextContentControl98.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl99
            // 
            this.richTextContentControl99.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl100
            // 
            this.richTextContentControl100.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl101
            // 
            this.richTextContentControl101.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl102
            // 
            this.richTextContentControl102.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl103
            // 
            this.richTextContentControl103.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl104
            // 
            this.richTextContentControl104.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl105
            // 
            this.richTextContentControl105.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl106
            // 
            this.richTextContentControl106.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl107
            // 
            this.richTextContentControl107.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl108
            // 
            this.richTextContentControl108.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl109
            // 
            this.richTextContentControl109.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl110
            // 
            this.richTextContentControl110.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl111
            // 
            this.richTextContentControl111.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl112
            // 
            this.richTextContentControl112.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl113
            // 
            this.richTextContentControl113.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl114
            // 
            this.richTextContentControl114.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl115
            // 
            this.richTextContentControl115.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl116
            // 
            this.richTextContentControl116.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl117
            // 
            this.richTextContentControl117.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl118
            // 
            this.richTextContentControl118.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl119
            // 
            this.richTextContentControl119.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl120
            // 
            this.richTextContentControl120.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl121
            // 
            this.richTextContentControl121.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl122
            // 
            this.richTextContentControl122.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl123
            // 
            this.richTextContentControl123.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl124
            // 
            this.richTextContentControl124.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl125
            // 
            this.richTextContentControl125.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // Interactive_Tender_Process
            // 
            this.Interactive_Tender_Process.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // Non_Price_Attributes
            // 
            this.Non_Price_Attributes.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // Pricing_Options
            // 
            this.Pricing_Options.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // Tender_Submission_Programme
            // 
            this.Tender_Submission_Programme.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // Contract_Details
            // 
            this.Contract_Details.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // Tender_Format
            // 
            this.Tender_Format.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // Tender_Evaluation_Procedure
            // 
            this.Tender_Evaluation_Procedure.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // Supplier_Selection_Method
            // 
            this.Supplier_Selection_Method.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // Contract_Pricing
            // 
            this.Contract_Pricing.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // Geotechnical_Testing_Schedule
            // 
            this.Geotechnical_Testing_Schedule.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // Additional_Services_Schedule
            // 
            this.Additional_Services_Schedule.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // Personnel_Schedule
            // 
            this.Personnel_Schedule.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // ThisDocument
            // 
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void OnShutdown() {
            this.Personnel_Schedule.Dispose();
            this.Additional_Services_Schedule.Dispose();
            this.Geotechnical_Testing_Schedule.Dispose();
            this.Contract_Pricing.Dispose();
            this.Supplier_Selection_Method.Dispose();
            this.Tender_Evaluation_Procedure.Dispose();
            this.Tender_Format.Dispose();
            this.Contract_Details.Dispose();
            this.Tender_Submission_Programme.Dispose();
            this.Pricing_Options.Dispose();
            this.Non_Price_Attributes.Dispose();
            this.Interactive_Tender_Process.Dispose();
            this.richTextContentControl125.Dispose();
            this.richTextContentControl124.Dispose();
            this.richTextContentControl123.Dispose();
            this.richTextContentControl122.Dispose();
            this.richTextContentControl121.Dispose();
            this.richTextContentControl120.Dispose();
            this.richTextContentControl119.Dispose();
            this.richTextContentControl118.Dispose();
            this.richTextContentControl117.Dispose();
            this.richTextContentControl116.Dispose();
            this.richTextContentControl115.Dispose();
            this.richTextContentControl114.Dispose();
            this.richTextContentControl113.Dispose();
            this.richTextContentControl112.Dispose();
            this.richTextContentControl111.Dispose();
            this.richTextContentControl110.Dispose();
            this.richTextContentControl109.Dispose();
            this.richTextContentControl108.Dispose();
            this.richTextContentControl107.Dispose();
            this.richTextContentControl106.Dispose();
            this.richTextContentControl105.Dispose();
            this.richTextContentControl104.Dispose();
            this.richTextContentControl103.Dispose();
            this.richTextContentControl102.Dispose();
            this.richTextContentControl101.Dispose();
            this.richTextContentControl100.Dispose();
            this.richTextContentControl99.Dispose();
            this.richTextContentControl98.Dispose();
            this.richTextContentControl97.Dispose();
            this.richTextContentControl96.Dispose();
            this.richTextContentControl95.Dispose();
            this.richTextContentControl94.Dispose();
            this.richTextContentControl93.Dispose();
            this.richTextContentControl92.Dispose();
            this.richTextContentControl91.Dispose();
            this.richTextContentControl90.Dispose();
            this.richTextContentControl89.Dispose();
            this.richTextContentControl88.Dispose();
            this.richTextContentControl87.Dispose();
            this.richTextContentControl86.Dispose();
            this.richTextContentControl85.Dispose();
            this.richTextContentControl84.Dispose();
            this.richTextContentControl83.Dispose();
            this.richTextContentControl82.Dispose();
            this.richTextContentControl81.Dispose();
            this.richTextContentControl80.Dispose();
            this.richTextContentControl79.Dispose();
            this.richTextContentControl78.Dispose();
            this.richTextContentControl77.Dispose();
            this.richTextContentControl76.Dispose();
            this.richTextContentControl75.Dispose();
            this.richTextContentControl74.Dispose();
            this.richTextContentControl73.Dispose();
            this.richTextContentControl72.Dispose();
            this.richTextContentControl71.Dispose();
            this.richTextContentControl70.Dispose();
            this.richTextContentControl69.Dispose();
            this.richTextContentControl68.Dispose();
            this.richTextContentControl67.Dispose();
            this.richTextContentControl66.Dispose();
            this.richTextContentControl65.Dispose();
            this.richTextContentControl64.Dispose();
            this.richTextContentControl63.Dispose();
            this.richTextContentControl62.Dispose();
            this.richTextContentControl61.Dispose();
            this.richTextContentControl60.Dispose();
            this.richTextContentControl59.Dispose();
            this.richTextContentControl58.Dispose();
            this.richTextContentControl57.Dispose();
            this.richTextContentControl56.Dispose();
            this.richTextContentControl55.Dispose();
            this.richTextContentControl54.Dispose();
            this.richTextContentControl53.Dispose();
            this.richTextContentControl52.Dispose();
            this.richTextContentControl51.Dispose();
            this.richTextContentControl50.Dispose();
            this.richTextContentControl49.Dispose();
            this.richTextContentControl48.Dispose();
            this.richTextContentControl47.Dispose();
            this.richTextContentControl46.Dispose();
            this.richTextContentControl45.Dispose();
            this.richTextContentControl44.Dispose();
            this.richTextContentControl43.Dispose();
            this.richTextContentControl41.Dispose();
            this.richTextContentControl40.Dispose();
            this.richTextContentControl39.Dispose();
            this.richTextContentControl38.Dispose();
            this.richTextContentControl37.Dispose();
            this.richTextContentControl36.Dispose();
            this.richTextContentControl35.Dispose();
            this.richTextContentControl34.Dispose();
            this.richTextContentControl33.Dispose();
            this.richTextContentControl32.Dispose();
            this.richTextContentControl31.Dispose();
            this.richTextContentControl30.Dispose();
            this.richTextContentControl29.Dispose();
            this.richTextContentControl28.Dispose();
            this.richTextContentControl27.Dispose();
            this.richTextContentControl26.Dispose();
            this.richTextContentControl25.Dispose();
            this.richTextContentControl24.Dispose();
            this.richTextContentControl23.Dispose();
            this.richTextContentControl1.Dispose();
            this.richTextContentControl22.Dispose();
            this.richTextContentControl21.Dispose();
            this.richTextContentControl20.Dispose();
            this.richTextContentControl19.Dispose();
            this.richTextContentControl18.Dispose();
            this.richTextContentControl17.Dispose();
            this.richTextContentControl16.Dispose();
            this.richTextContentControl15.Dispose();
            this.richTextContentControl14.Dispose();
            this.richTextContentControl13.Dispose();
            this.richTextContentControl12.Dispose();
            this.richTextContentControl11.Dispose();
            this.richTextContentControl10.Dispose();
            this.richTextContentControl9.Dispose();
            this.richTextContentControl8.Dispose();
            this.richTextContentControl7.Dispose();
            this.richTextContentControl6.Dispose();
            this.richTextContentControl5.Dispose();
            this.richTextContentControl4.Dispose();
            this.richTextContentControl3.Dispose();
            this.richTextContentControl2.Dispose();
            this.ActionsPane.Dispose();
            base.OnShutdown();
        }
    }
    
    /// 
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
    internal sealed partial class Globals {
        
        /// 
        private Globals() {
        }
        
        private static ThisDocument _ThisDocument;
        
        private static global::Microsoft.Office.Tools.Word.Factory _factory;
        
        private static ThisRibbonCollection _ThisRibbonCollection;
        
        internal static ThisDocument ThisDocument {
            get {
                return _ThisDocument;
            }
            set {
                if ((_ThisDocument == null)) {
                    _ThisDocument = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
        
        internal static global::Microsoft.Office.Tools.Word.Factory Factory {
            get {
                return _factory;
            }
            set {
                if ((_factory == null)) {
                    _factory = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
        
        internal static ThisRibbonCollection Ribbons {
            get {
                if ((_ThisRibbonCollection == null)) {
                    _ThisRibbonCollection = new ThisRibbonCollection(_factory.GetRibbonFactory());
                }
                return _ThisRibbonCollection;
            }
        }
    }
    
    /// 
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
    internal sealed partial class ThisRibbonCollection : Microsoft.Office.Tools.Ribbon.RibbonCollectionBase {
        
        /// 
        internal ThisRibbonCollection(global::Microsoft.Office.Tools.Ribbon.RibbonFactory factory) : 
                base(factory) {
        }
    }
}
