//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace NZTA_Contract_Generator {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(0)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class ThisDocument : Microsoft.Office.Tools.Word.DocumentBase {
        
        internal Microsoft.Office.Tools.ActionsPane ActionsPane;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl144;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl145;
        
        internal Microsoft.Office.Tools.Word.Bookmark Additional_Services_Schedule;
        
        internal Microsoft.Office.Tools.Word.Bookmark Contract_Details;
        
        internal Microsoft.Office.Tools.Word.Bookmark Contract_Pricing;
        
        internal Microsoft.Office.Tools.Word.Bookmark Geotechnical_Testing_Schedule;
        
        internal Microsoft.Office.Tools.Word.Bookmark Interactive_Tender_Process;
        
        internal Microsoft.Office.Tools.Word.Bookmark Non_Price_Attributes;
        
        internal Microsoft.Office.Tools.Word.Bookmark Personnel_Schedule;
        
        internal Microsoft.Office.Tools.Word.Bookmark Pricing_Options;
        
        internal Microsoft.Office.Tools.Word.Bookmark Supplier_Selection_Method;
        
        internal Microsoft.Office.Tools.Word.Bookmark Tender_Evaluation_Procedure;
        
        internal Microsoft.Office.Tools.Word.Bookmark Tender_Format;
        
        internal Microsoft.Office.Tools.Word.Bookmark Tender_Submission_Programme;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl1;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl146;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl147;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl153;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl154;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl155;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl156;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl157;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl158;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl159;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl160;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl161;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl162;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl163;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl164;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl165;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl166;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl167;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl168;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl169;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl170;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl171;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl172;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl173;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl174;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl175;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl176;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl177;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl178;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl179;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl180;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl181;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl182;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl183;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl184;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl185;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl186;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl187;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl188;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl189;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl190;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl191;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl192;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl193;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl194;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl195;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl196;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl197;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl198;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl199;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl200;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl201;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl202;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl203;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl204;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl205;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl206;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl207;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl208;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl209;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl210;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl211;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl212;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl213;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl214;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl215;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl216;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl217;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl218;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl219;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl220;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl221;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl222;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl223;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl224;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl225;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl226;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl227;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl228;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl229;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl230;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl231;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl232;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl233;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl234;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl235;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl236;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl237;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl238;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl239;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl240;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl241;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl242;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl243;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl244;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl245;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl246;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl247;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl248;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl249;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl250;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl251;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl252;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl253;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl254;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl255;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl256;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl257;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl258;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl259;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl260;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl261;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl262;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl263;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl264;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl265;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl266;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl267;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl268;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl269;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl270;
        
        internal Microsoft.Office.Tools.Word.RichTextContentControl richTextContentControl271;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        internal Microsoft.Office.Interop.Word.Application ThisApplication;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public ThisDocument(global::Microsoft.Office.Tools.Word.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "ThisDocument", "ThisDocument") {
            Globals.Factory = factory;
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            this.ThisApplication = this.GetHostItem<Microsoft.Office.Interop.Word.Application>(typeof(Microsoft.Office.Interop.Word.Application), "Application");
            Globals.ThisDocument = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
            this.ActionsPane.BeginInit();
            this.richTextContentControl144.BeginInit();
            this.richTextContentControl145.BeginInit();
            this.Additional_Services_Schedule.BeginInit();
            this.Contract_Details.BeginInit();
            this.Contract_Pricing.BeginInit();
            this.Geotechnical_Testing_Schedule.BeginInit();
            this.Interactive_Tender_Process.BeginInit();
            this.Non_Price_Attributes.BeginInit();
            this.Personnel_Schedule.BeginInit();
            this.Pricing_Options.BeginInit();
            this.Supplier_Selection_Method.BeginInit();
            this.Tender_Evaluation_Procedure.BeginInit();
            this.Tender_Format.BeginInit();
            this.Tender_Submission_Programme.BeginInit();
            this.richTextContentControl1.BeginInit();
            this.richTextContentControl146.BeginInit();
            this.richTextContentControl147.BeginInit();
            this.richTextContentControl153.BeginInit();
            this.richTextContentControl154.BeginInit();
            this.richTextContentControl155.BeginInit();
            this.richTextContentControl156.BeginInit();
            this.richTextContentControl157.BeginInit();
            this.richTextContentControl158.BeginInit();
            this.richTextContentControl159.BeginInit();
            this.richTextContentControl160.BeginInit();
            this.richTextContentControl161.BeginInit();
            this.richTextContentControl162.BeginInit();
            this.richTextContentControl163.BeginInit();
            this.richTextContentControl164.BeginInit();
            this.richTextContentControl165.BeginInit();
            this.richTextContentControl166.BeginInit();
            this.richTextContentControl167.BeginInit();
            this.richTextContentControl168.BeginInit();
            this.richTextContentControl169.BeginInit();
            this.richTextContentControl170.BeginInit();
            this.richTextContentControl171.BeginInit();
            this.richTextContentControl172.BeginInit();
            this.richTextContentControl173.BeginInit();
            this.richTextContentControl174.BeginInit();
            this.richTextContentControl175.BeginInit();
            this.richTextContentControl176.BeginInit();
            this.richTextContentControl177.BeginInit();
            this.richTextContentControl178.BeginInit();
            this.richTextContentControl179.BeginInit();
            this.richTextContentControl180.BeginInit();
            this.richTextContentControl181.BeginInit();
            this.richTextContentControl182.BeginInit();
            this.richTextContentControl183.BeginInit();
            this.richTextContentControl184.BeginInit();
            this.richTextContentControl185.BeginInit();
            this.richTextContentControl186.BeginInit();
            this.richTextContentControl187.BeginInit();
            this.richTextContentControl188.BeginInit();
            this.richTextContentControl189.BeginInit();
            this.richTextContentControl190.BeginInit();
            this.richTextContentControl191.BeginInit();
            this.richTextContentControl192.BeginInit();
            this.richTextContentControl193.BeginInit();
            this.richTextContentControl194.BeginInit();
            this.richTextContentControl195.BeginInit();
            this.richTextContentControl196.BeginInit();
            this.richTextContentControl197.BeginInit();
            this.richTextContentControl198.BeginInit();
            this.richTextContentControl199.BeginInit();
            this.richTextContentControl200.BeginInit();
            this.richTextContentControl201.BeginInit();
            this.richTextContentControl202.BeginInit();
            this.richTextContentControl203.BeginInit();
            this.richTextContentControl204.BeginInit();
            this.richTextContentControl205.BeginInit();
            this.richTextContentControl206.BeginInit();
            this.richTextContentControl207.BeginInit();
            this.richTextContentControl208.BeginInit();
            this.richTextContentControl209.BeginInit();
            this.richTextContentControl210.BeginInit();
            this.richTextContentControl211.BeginInit();
            this.richTextContentControl212.BeginInit();
            this.richTextContentControl213.BeginInit();
            this.richTextContentControl214.BeginInit();
            this.richTextContentControl215.BeginInit();
            this.richTextContentControl216.BeginInit();
            this.richTextContentControl217.BeginInit();
            this.richTextContentControl218.BeginInit();
            this.richTextContentControl219.BeginInit();
            this.richTextContentControl220.BeginInit();
            this.richTextContentControl221.BeginInit();
            this.richTextContentControl222.BeginInit();
            this.richTextContentControl223.BeginInit();
            this.richTextContentControl224.BeginInit();
            this.richTextContentControl225.BeginInit();
            this.richTextContentControl226.BeginInit();
            this.richTextContentControl227.BeginInit();
            this.richTextContentControl228.BeginInit();
            this.richTextContentControl229.BeginInit();
            this.richTextContentControl230.BeginInit();
            this.richTextContentControl231.BeginInit();
            this.richTextContentControl232.BeginInit();
            this.richTextContentControl233.BeginInit();
            this.richTextContentControl234.BeginInit();
            this.richTextContentControl235.BeginInit();
            this.richTextContentControl236.BeginInit();
            this.richTextContentControl237.BeginInit();
            this.richTextContentControl238.BeginInit();
            this.richTextContentControl239.BeginInit();
            this.richTextContentControl240.BeginInit();
            this.richTextContentControl241.BeginInit();
            this.richTextContentControl242.BeginInit();
            this.richTextContentControl243.BeginInit();
            this.richTextContentControl244.BeginInit();
            this.richTextContentControl245.BeginInit();
            this.richTextContentControl246.BeginInit();
            this.richTextContentControl247.BeginInit();
            this.richTextContentControl248.BeginInit();
            this.richTextContentControl249.BeginInit();
            this.richTextContentControl250.BeginInit();
            this.richTextContentControl251.BeginInit();
            this.richTextContentControl252.BeginInit();
            this.richTextContentControl253.BeginInit();
            this.richTextContentControl254.BeginInit();
            this.richTextContentControl255.BeginInit();
            this.richTextContentControl256.BeginInit();
            this.richTextContentControl257.BeginInit();
            this.richTextContentControl258.BeginInit();
            this.richTextContentControl259.BeginInit();
            this.richTextContentControl260.BeginInit();
            this.richTextContentControl261.BeginInit();
            this.richTextContentControl262.BeginInit();
            this.richTextContentControl263.BeginInit();
            this.richTextContentControl264.BeginInit();
            this.richTextContentControl265.BeginInit();
            this.richTextContentControl266.BeginInit();
            this.richTextContentControl267.BeginInit();
            this.richTextContentControl268.BeginInit();
            this.richTextContentControl269.BeginInit();
            this.richTextContentControl270.BeginInit();
            this.richTextContentControl271.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.richTextContentControl271.EndInit();
            this.richTextContentControl270.EndInit();
            this.richTextContentControl269.EndInit();
            this.richTextContentControl268.EndInit();
            this.richTextContentControl267.EndInit();
            this.richTextContentControl266.EndInit();
            this.richTextContentControl265.EndInit();
            this.richTextContentControl264.EndInit();
            this.richTextContentControl263.EndInit();
            this.richTextContentControl262.EndInit();
            this.richTextContentControl261.EndInit();
            this.richTextContentControl260.EndInit();
            this.richTextContentControl259.EndInit();
            this.richTextContentControl258.EndInit();
            this.richTextContentControl257.EndInit();
            this.richTextContentControl256.EndInit();
            this.richTextContentControl255.EndInit();
            this.richTextContentControl254.EndInit();
            this.richTextContentControl253.EndInit();
            this.richTextContentControl252.EndInit();
            this.richTextContentControl251.EndInit();
            this.richTextContentControl250.EndInit();
            this.richTextContentControl249.EndInit();
            this.richTextContentControl248.EndInit();
            this.richTextContentControl247.EndInit();
            this.richTextContentControl246.EndInit();
            this.richTextContentControl245.EndInit();
            this.richTextContentControl244.EndInit();
            this.richTextContentControl243.EndInit();
            this.richTextContentControl242.EndInit();
            this.richTextContentControl241.EndInit();
            this.richTextContentControl240.EndInit();
            this.richTextContentControl239.EndInit();
            this.richTextContentControl238.EndInit();
            this.richTextContentControl237.EndInit();
            this.richTextContentControl236.EndInit();
            this.richTextContentControl235.EndInit();
            this.richTextContentControl234.EndInit();
            this.richTextContentControl233.EndInit();
            this.richTextContentControl232.EndInit();
            this.richTextContentControl231.EndInit();
            this.richTextContentControl230.EndInit();
            this.richTextContentControl229.EndInit();
            this.richTextContentControl228.EndInit();
            this.richTextContentControl227.EndInit();
            this.richTextContentControl226.EndInit();
            this.richTextContentControl225.EndInit();
            this.richTextContentControl224.EndInit();
            this.richTextContentControl223.EndInit();
            this.richTextContentControl222.EndInit();
            this.richTextContentControl221.EndInit();
            this.richTextContentControl220.EndInit();
            this.richTextContentControl219.EndInit();
            this.richTextContentControl218.EndInit();
            this.richTextContentControl217.EndInit();
            this.richTextContentControl216.EndInit();
            this.richTextContentControl215.EndInit();
            this.richTextContentControl214.EndInit();
            this.richTextContentControl213.EndInit();
            this.richTextContentControl212.EndInit();
            this.richTextContentControl211.EndInit();
            this.richTextContentControl210.EndInit();
            this.richTextContentControl209.EndInit();
            this.richTextContentControl208.EndInit();
            this.richTextContentControl207.EndInit();
            this.richTextContentControl206.EndInit();
            this.richTextContentControl205.EndInit();
            this.richTextContentControl204.EndInit();
            this.richTextContentControl203.EndInit();
            this.richTextContentControl202.EndInit();
            this.richTextContentControl201.EndInit();
            this.richTextContentControl200.EndInit();
            this.richTextContentControl199.EndInit();
            this.richTextContentControl198.EndInit();
            this.richTextContentControl197.EndInit();
            this.richTextContentControl196.EndInit();
            this.richTextContentControl195.EndInit();
            this.richTextContentControl194.EndInit();
            this.richTextContentControl193.EndInit();
            this.richTextContentControl192.EndInit();
            this.richTextContentControl191.EndInit();
            this.richTextContentControl190.EndInit();
            this.richTextContentControl189.EndInit();
            this.richTextContentControl188.EndInit();
            this.richTextContentControl187.EndInit();
            this.richTextContentControl186.EndInit();
            this.richTextContentControl185.EndInit();
            this.richTextContentControl184.EndInit();
            this.richTextContentControl183.EndInit();
            this.richTextContentControl182.EndInit();
            this.richTextContentControl181.EndInit();
            this.richTextContentControl180.EndInit();
            this.richTextContentControl179.EndInit();
            this.richTextContentControl178.EndInit();
            this.richTextContentControl177.EndInit();
            this.richTextContentControl176.EndInit();
            this.richTextContentControl175.EndInit();
            this.richTextContentControl174.EndInit();
            this.richTextContentControl173.EndInit();
            this.richTextContentControl172.EndInit();
            this.richTextContentControl171.EndInit();
            this.richTextContentControl170.EndInit();
            this.richTextContentControl169.EndInit();
            this.richTextContentControl168.EndInit();
            this.richTextContentControl167.EndInit();
            this.richTextContentControl166.EndInit();
            this.richTextContentControl165.EndInit();
            this.richTextContentControl164.EndInit();
            this.richTextContentControl163.EndInit();
            this.richTextContentControl162.EndInit();
            this.richTextContentControl161.EndInit();
            this.richTextContentControl160.EndInit();
            this.richTextContentControl159.EndInit();
            this.richTextContentControl158.EndInit();
            this.richTextContentControl157.EndInit();
            this.richTextContentControl156.EndInit();
            this.richTextContentControl155.EndInit();
            this.richTextContentControl154.EndInit();
            this.richTextContentControl153.EndInit();
            this.richTextContentControl147.EndInit();
            this.richTextContentControl146.EndInit();
            this.richTextContentControl1.EndInit();
            this.Tender_Submission_Programme.EndInit();
            this.Tender_Format.EndInit();
            this.Tender_Evaluation_Procedure.EndInit();
            this.Supplier_Selection_Method.EndInit();
            this.Pricing_Options.EndInit();
            this.Personnel_Schedule.EndInit();
            this.Non_Price_Attributes.EndInit();
            this.Interactive_Tender_Process.EndInit();
            this.Geotechnical_Testing_Schedule.EndInit();
            this.Contract_Pricing.EndInit();
            this.Contract_Details.EndInit();
            this.Additional_Services_Schedule.EndInit();
            this.richTextContentControl145.EndInit();
            this.richTextContentControl144.EndInit();
            this.ActionsPane.EndInit();
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.ActionsPane = Globals.Factory.CreateActionsPane(null, null, "ActionsPane", "ActionsPane", this);
            this.richTextContentControl144 = Globals.Factory.CreateRichTextContentControl(null, null, "1152408033", "richTextContentControl144", this);
            this.richTextContentControl145 = Globals.Factory.CreateRichTextContentControl(null, null, "2809499199", "richTextContentControl145", this);
            this.Additional_Services_Schedule = Globals.Factory.CreateBookmark(null, null, "Additional_Services_Schedule", "Additional_Services_Schedule", this);
            this.Contract_Details = Globals.Factory.CreateBookmark(null, null, "Contract_Details", "Contract_Details", this);
            this.Contract_Pricing = Globals.Factory.CreateBookmark(null, null, "Contract_Pricing", "Contract_Pricing", this);
            this.Geotechnical_Testing_Schedule = Globals.Factory.CreateBookmark(null, null, "Geotechnical_Testing_Schedule", "Geotechnical_Testing_Schedule", this);
            this.Interactive_Tender_Process = Globals.Factory.CreateBookmark(null, null, "Interactive_Tender_Process", "Interactive_Tender_Process", this);
            this.Non_Price_Attributes = Globals.Factory.CreateBookmark(null, null, "Non_Price_Attributes", "Non_Price_Attributes", this);
            this.Personnel_Schedule = Globals.Factory.CreateBookmark(null, null, "Personnel_Schedule", "Personnel_Schedule", this);
            this.Pricing_Options = Globals.Factory.CreateBookmark(null, null, "Pricing_Options", "Pricing_Options", this);
            this.Supplier_Selection_Method = Globals.Factory.CreateBookmark(null, null, "Supplier_Selection_Method", "Supplier_Selection_Method", this);
            this.Tender_Evaluation_Procedure = Globals.Factory.CreateBookmark(null, null, "Tender_Evaluation_Procedure", "Tender_Evaluation_Procedure", this);
            this.Tender_Format = Globals.Factory.CreateBookmark(null, null, "Tender_Format", "Tender_Format", this);
            this.Tender_Submission_Programme = Globals.Factory.CreateBookmark(null, null, "Tender_Submission_Programme", "Tender_Submission_Programme", this);
            this.richTextContentControl1 = Globals.Factory.CreateRichTextContentControl(null, null, "2995438561", "richTextContentControl1", this);
            this.richTextContentControl146 = Globals.Factory.CreateRichTextContentControl(null, null, "3011478966", "richTextContentControl146", this);
            this.richTextContentControl147 = Globals.Factory.CreateRichTextContentControl(null, null, "1839502725", "richTextContentControl147", this);
            this.richTextContentControl153 = Globals.Factory.CreateRichTextContentControl(null, null, "48886945", "richTextContentControl153", this);
            this.richTextContentControl154 = Globals.Factory.CreateRichTextContentControl(null, null, "872501667", "richTextContentControl154", this);
            this.richTextContentControl155 = Globals.Factory.CreateRichTextContentControl(null, null, "393324230", "richTextContentControl155", this);
            this.richTextContentControl156 = Globals.Factory.CreateRichTextContentControl(null, null, "1695653966", "richTextContentControl156", this);
            this.richTextContentControl157 = Globals.Factory.CreateRichTextContentControl(null, null, "662434785", "richTextContentControl157", this);
            this.richTextContentControl158 = Globals.Factory.CreateRichTextContentControl(null, null, "1792243549", "richTextContentControl158", this);
            this.richTextContentControl159 = Globals.Factory.CreateRichTextContentControl(null, null, "2271507081", "richTextContentControl159", this);
            this.richTextContentControl160 = Globals.Factory.CreateRichTextContentControl(null, null, "74411214", "richTextContentControl160", this);
            this.richTextContentControl161 = Globals.Factory.CreateRichTextContentControl(null, null, "460859104", "richTextContentControl161", this);
            this.richTextContentControl162 = Globals.Factory.CreateRichTextContentControl(null, null, "2438016426", "richTextContentControl162", this);
            this.richTextContentControl163 = Globals.Factory.CreateRichTextContentControl(null, null, "4135955664", "richTextContentControl163", this);
            this.richTextContentControl164 = Globals.Factory.CreateRichTextContentControl(null, null, "2476395455", "richTextContentControl164", this);
            this.richTextContentControl165 = Globals.Factory.CreateRichTextContentControl(null, null, "2929223368", "richTextContentControl165", this);
            this.richTextContentControl166 = Globals.Factory.CreateRichTextContentControl(null, null, "1585649752", "richTextContentControl166", this);
            this.richTextContentControl167 = Globals.Factory.CreateRichTextContentControl(null, null, "321312835", "richTextContentControl167", this);
            this.richTextContentControl168 = Globals.Factory.CreateRichTextContentControl(null, null, "2628732258", "richTextContentControl168", this);
            this.richTextContentControl169 = Globals.Factory.CreateRichTextContentControl(null, null, "725884906", "richTextContentControl169", this);
            this.richTextContentControl170 = Globals.Factory.CreateRichTextContentControl(null, null, "4137966592", "richTextContentControl170", this);
            this.richTextContentControl171 = Globals.Factory.CreateRichTextContentControl(null, null, "1603068122", "richTextContentControl171", this);
            this.richTextContentControl172 = Globals.Factory.CreateRichTextContentControl(null, null, "1668204497", "richTextContentControl172", this);
            this.richTextContentControl173 = Globals.Factory.CreateRichTextContentControl(null, null, "3899370984", "richTextContentControl173", this);
            this.richTextContentControl174 = Globals.Factory.CreateRichTextContentControl(null, null, "312373938", "richTextContentControl174", this);
            this.richTextContentControl175 = Globals.Factory.CreateRichTextContentControl(null, null, "1661040138", "richTextContentControl175", this);
            this.richTextContentControl176 = Globals.Factory.CreateRichTextContentControl(null, null, "520352158", "richTextContentControl176", this);
            this.richTextContentControl177 = Globals.Factory.CreateRichTextContentControl(null, null, "3000989983", "richTextContentControl177", this);
            this.richTextContentControl178 = Globals.Factory.CreateRichTextContentControl(null, null, "869421511", "richTextContentControl178", this);
            this.richTextContentControl179 = Globals.Factory.CreateRichTextContentControl(null, null, "3172821666", "richTextContentControl179", this);
            this.richTextContentControl180 = Globals.Factory.CreateRichTextContentControl(null, null, "46739209", "richTextContentControl180", this);
            this.richTextContentControl181 = Globals.Factory.CreateRichTextContentControl(null, null, "1227035432", "richTextContentControl181", this);
            this.richTextContentControl182 = Globals.Factory.CreateRichTextContentControl(null, null, "795332043", "richTextContentControl182", this);
            this.richTextContentControl183 = Globals.Factory.CreateRichTextContentControl(null, null, "799043528", "richTextContentControl183", this);
            this.richTextContentControl184 = Globals.Factory.CreateRichTextContentControl(null, null, "3806717593", "richTextContentControl184", this);
            this.richTextContentControl185 = Globals.Factory.CreateRichTextContentControl(null, null, "4203496865", "richTextContentControl185", this);
            this.richTextContentControl186 = Globals.Factory.CreateRichTextContentControl(null, null, "2029049825", "richTextContentControl186", this);
            this.richTextContentControl187 = Globals.Factory.CreateRichTextContentControl(null, null, "2246138551", "richTextContentControl187", this);
            this.richTextContentControl188 = Globals.Factory.CreateRichTextContentControl(null, null, "4159626105", "richTextContentControl188", this);
            this.richTextContentControl189 = Globals.Factory.CreateRichTextContentControl(null, null, "131995785", "richTextContentControl189", this);
            this.richTextContentControl190 = Globals.Factory.CreateRichTextContentControl(null, null, "2451507104", "richTextContentControl190", this);
            this.richTextContentControl191 = Globals.Factory.CreateRichTextContentControl(null, null, "3877098858", "richTextContentControl191", this);
            this.richTextContentControl192 = Globals.Factory.CreateRichTextContentControl(null, null, "1560362615", "richTextContentControl192", this);
            this.richTextContentControl193 = Globals.Factory.CreateRichTextContentControl(null, null, "272366006", "richTextContentControl193", this);
            this.richTextContentControl194 = Globals.Factory.CreateRichTextContentControl(null, null, "3929831446", "richTextContentControl194", this);
            this.richTextContentControl195 = Globals.Factory.CreateRichTextContentControl(null, null, "1162047053", "richTextContentControl195", this);
            this.richTextContentControl196 = Globals.Factory.CreateRichTextContentControl(null, null, "447735765", "richTextContentControl196", this);
            this.richTextContentControl197 = Globals.Factory.CreateRichTextContentControl(null, null, "941338972", "richTextContentControl197", this);
            this.richTextContentControl198 = Globals.Factory.CreateRichTextContentControl(null, null, "341986538", "richTextContentControl198", this);
            this.richTextContentControl199 = Globals.Factory.CreateRichTextContentControl(null, null, "69089062", "richTextContentControl199", this);
            this.richTextContentControl200 = Globals.Factory.CreateRichTextContentControl(null, null, "109629875", "richTextContentControl200", this);
            this.richTextContentControl201 = Globals.Factory.CreateRichTextContentControl(null, null, "657958454", "richTextContentControl201", this);
            this.richTextContentControl202 = Globals.Factory.CreateRichTextContentControl(null, null, "3563351903", "richTextContentControl202", this);
            this.richTextContentControl203 = Globals.Factory.CreateRichTextContentControl(null, null, "3909930918", "richTextContentControl203", this);
            this.richTextContentControl204 = Globals.Factory.CreateRichTextContentControl(null, null, "2141539433", "richTextContentControl204", this);
            this.richTextContentControl205 = Globals.Factory.CreateRichTextContentControl(null, null, "1853837190", "richTextContentControl205", this);
            this.richTextContentControl206 = Globals.Factory.CreateRichTextContentControl(null, null, "1366956474", "richTextContentControl206", this);
            this.richTextContentControl207 = Globals.Factory.CreateRichTextContentControl(null, null, "840744964", "richTextContentControl207", this);
            this.richTextContentControl208 = Globals.Factory.CreateRichTextContentControl(null, null, "1312837409", "richTextContentControl208", this);
            this.richTextContentControl209 = Globals.Factory.CreateRichTextContentControl(null, null, "2173434664", "richTextContentControl209", this);
            this.richTextContentControl210 = Globals.Factory.CreateRichTextContentControl(null, null, "1401248721", "richTextContentControl210", this);
            this.richTextContentControl211 = Globals.Factory.CreateRichTextContentControl(null, null, "1823993579", "richTextContentControl211", this);
            this.richTextContentControl212 = Globals.Factory.CreateRichTextContentControl(null, null, "418218952", "richTextContentControl212", this);
            this.richTextContentControl213 = Globals.Factory.CreateRichTextContentControl(null, null, "3906922201", "richTextContentControl213", this);
            this.richTextContentControl214 = Globals.Factory.CreateRichTextContentControl(null, null, "1328790965", "richTextContentControl214", this);
            this.richTextContentControl215 = Globals.Factory.CreateRichTextContentControl(null, null, "850064440", "richTextContentControl215", this);
            this.richTextContentControl216 = Globals.Factory.CreateRichTextContentControl(null, null, "136778827", "richTextContentControl216", this);
            this.richTextContentControl217 = Globals.Factory.CreateRichTextContentControl(null, null, "3287983803", "richTextContentControl217", this);
            this.richTextContentControl218 = Globals.Factory.CreateRichTextContentControl(null, null, "3822673428", "richTextContentControl218", this);
            this.richTextContentControl219 = Globals.Factory.CreateRichTextContentControl(null, null, "3385651841", "richTextContentControl219", this);
            this.richTextContentControl220 = Globals.Factory.CreateRichTextContentControl(null, null, "3670354976", "richTextContentControl220", this);
            this.richTextContentControl221 = Globals.Factory.CreateRichTextContentControl(null, null, "516509744", "richTextContentControl221", this);
            this.richTextContentControl222 = Globals.Factory.CreateRichTextContentControl(null, null, "2764631749", "richTextContentControl222", this);
            this.richTextContentControl223 = Globals.Factory.CreateRichTextContentControl(null, null, "1383983299", "richTextContentControl223", this);
            this.richTextContentControl224 = Globals.Factory.CreateRichTextContentControl(null, null, "4059557857", "richTextContentControl224", this);
            this.richTextContentControl225 = Globals.Factory.CreateRichTextContentControl(null, null, "4097488767", "richTextContentControl225", this);
            this.richTextContentControl226 = Globals.Factory.CreateRichTextContentControl(null, null, "379295691", "richTextContentControl226", this);
            this.richTextContentControl227 = Globals.Factory.CreateRichTextContentControl(null, null, "2950499455", "richTextContentControl227", this);
            this.richTextContentControl228 = Globals.Factory.CreateRichTextContentControl(null, null, "4117237585", "richTextContentControl228", this);
            this.richTextContentControl229 = Globals.Factory.CreateRichTextContentControl(null, null, "3945868115", "richTextContentControl229", this);
            this.richTextContentControl230 = Globals.Factory.CreateRichTextContentControl(null, null, "251789873", "richTextContentControl230", this);
            this.richTextContentControl231 = Globals.Factory.CreateRichTextContentControl(null, null, "3173909173", "richTextContentControl231", this);
            this.richTextContentControl232 = Globals.Factory.CreateRichTextContentControl(null, null, "860010837", "richTextContentControl232", this);
            this.richTextContentControl233 = Globals.Factory.CreateRichTextContentControl(null, null, "3480546701", "richTextContentControl233", this);
            this.richTextContentControl234 = Globals.Factory.CreateRichTextContentControl(null, null, "3054182277", "richTextContentControl234", this);
            this.richTextContentControl235 = Globals.Factory.CreateRichTextContentControl(null, null, "1275054114", "richTextContentControl235", this);
            this.richTextContentControl236 = Globals.Factory.CreateRichTextContentControl(null, null, "632604631", "richTextContentControl236", this);
            this.richTextContentControl237 = Globals.Factory.CreateRichTextContentControl(null, null, "2456515144", "richTextContentControl237", this);
            this.richTextContentControl238 = Globals.Factory.CreateRichTextContentControl(null, null, "3649845009", "richTextContentControl238", this);
            this.richTextContentControl239 = Globals.Factory.CreateRichTextContentControl(null, null, "4213202597", "richTextContentControl239", this);
            this.richTextContentControl240 = Globals.Factory.CreateRichTextContentControl(null, null, "2083798432", "richTextContentControl240", this);
            this.richTextContentControl241 = Globals.Factory.CreateRichTextContentControl(null, null, "3777121332", "richTextContentControl241", this);
            this.richTextContentControl242 = Globals.Factory.CreateRichTextContentControl(null, null, "699198431", "richTextContentControl242", this);
            this.richTextContentControl243 = Globals.Factory.CreateRichTextContentControl(null, null, "1699817685", "richTextContentControl243", this);
            this.richTextContentControl244 = Globals.Factory.CreateRichTextContentControl(null, null, "2892361494", "richTextContentControl244", this);
            this.richTextContentControl245 = Globals.Factory.CreateRichTextContentControl(null, null, "1055048864", "richTextContentControl245", this);
            this.richTextContentControl246 = Globals.Factory.CreateRichTextContentControl(null, null, "3426907381", "richTextContentControl246", this);
            this.richTextContentControl247 = Globals.Factory.CreateRichTextContentControl(null, null, "2356379687", "richTextContentControl247", this);
            this.richTextContentControl248 = Globals.Factory.CreateRichTextContentControl(null, null, "2622796836", "richTextContentControl248", this);
            this.richTextContentControl249 = Globals.Factory.CreateRichTextContentControl(null, null, "1162504390", "richTextContentControl249", this);
            this.richTextContentControl250 = Globals.Factory.CreateRichTextContentControl(null, null, "47584081", "richTextContentControl250", this);
            this.richTextContentControl251 = Globals.Factory.CreateRichTextContentControl(null, null, "307831456", "richTextContentControl251", this);
            this.richTextContentControl252 = Globals.Factory.CreateRichTextContentControl(null, null, "1672835320", "richTextContentControl252", this);
            this.richTextContentControl253 = Globals.Factory.CreateRichTextContentControl(null, null, "1338034255", "richTextContentControl253", this);
            this.richTextContentControl254 = Globals.Factory.CreateRichTextContentControl(null, null, "2922898581", "richTextContentControl254", this);
            this.richTextContentControl255 = Globals.Factory.CreateRichTextContentControl(null, null, "946731594", "richTextContentControl255", this);
            this.richTextContentControl256 = Globals.Factory.CreateRichTextContentControl(null, null, "4137893328", "richTextContentControl256", this);
            this.richTextContentControl257 = Globals.Factory.CreateRichTextContentControl(null, null, "2223713893", "richTextContentControl257", this);
            this.richTextContentControl258 = Globals.Factory.CreateRichTextContentControl(null, null, "1442416395", "richTextContentControl258", this);
            this.richTextContentControl259 = Globals.Factory.CreateRichTextContentControl(null, null, "2940018876", "richTextContentControl259", this);
            this.richTextContentControl260 = Globals.Factory.CreateRichTextContentControl(null, null, "900637968", "richTextContentControl260", this);
            this.richTextContentControl261 = Globals.Factory.CreateRichTextContentControl(null, null, "3322219477", "richTextContentControl261", this);
            this.richTextContentControl262 = Globals.Factory.CreateRichTextContentControl(null, null, "773056331", "richTextContentControl262", this);
            this.richTextContentControl263 = Globals.Factory.CreateRichTextContentControl(null, null, "1632279992", "richTextContentControl263", this);
            this.richTextContentControl264 = Globals.Factory.CreateRichTextContentControl(null, null, "4248128866", "richTextContentControl264", this);
            this.richTextContentControl265 = Globals.Factory.CreateRichTextContentControl(null, null, "1181942687", "richTextContentControl265", this);
            this.richTextContentControl266 = Globals.Factory.CreateRichTextContentControl(null, null, "750698887", "richTextContentControl266", this);
            this.richTextContentControl267 = Globals.Factory.CreateRichTextContentControl(null, null, "2133434360", "richTextContentControl267", this);
            this.richTextContentControl268 = Globals.Factory.CreateRichTextContentControl(null, null, "1139070360", "richTextContentControl268", this);
            this.richTextContentControl269 = Globals.Factory.CreateRichTextContentControl(null, null, "1673536519", "richTextContentControl269", this);
            this.richTextContentControl270 = Globals.Factory.CreateRichTextContentControl(null, null, "1556360508", "richTextContentControl270", this);
            this.richTextContentControl271 = Globals.Factory.CreateRichTextContentControl(null, null, "2759396735", "richTextContentControl271", this);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            // 
            // ActionsPane
            // 
            this.ActionsPane.AutoSize = false;
            this.ActionsPane.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            // 
            // richTextContentControl144
            // 
            this.richTextContentControl144.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl145
            // 
            this.richTextContentControl145.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // Additional_Services_Schedule
            // 
            this.Additional_Services_Schedule.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // Contract_Details
            // 
            this.Contract_Details.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // Contract_Pricing
            // 
            this.Contract_Pricing.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // Geotechnical_Testing_Schedule
            // 
            this.Geotechnical_Testing_Schedule.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // Interactive_Tender_Process
            // 
            this.Interactive_Tender_Process.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // Non_Price_Attributes
            // 
            this.Non_Price_Attributes.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // Personnel_Schedule
            // 
            this.Personnel_Schedule.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // Pricing_Options
            // 
            this.Pricing_Options.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // Supplier_Selection_Method
            // 
            this.Supplier_Selection_Method.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // Tender_Evaluation_Procedure
            // 
            this.Tender_Evaluation_Procedure.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // Tender_Format
            // 
            this.Tender_Format.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // Tender_Submission_Programme
            // 
            this.Tender_Submission_Programme.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl1
            // 
            this.richTextContentControl1.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl146
            // 
            this.richTextContentControl146.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl147
            // 
            this.richTextContentControl147.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl153
            // 
            this.richTextContentControl153.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl154
            // 
            this.richTextContentControl154.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl155
            // 
            this.richTextContentControl155.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl156
            // 
            this.richTextContentControl156.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl157
            // 
            this.richTextContentControl157.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl158
            // 
            this.richTextContentControl158.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl159
            // 
            this.richTextContentControl159.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl160
            // 
            this.richTextContentControl160.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl161
            // 
            this.richTextContentControl161.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl162
            // 
            this.richTextContentControl162.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl163
            // 
            this.richTextContentControl163.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl164
            // 
            this.richTextContentControl164.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl165
            // 
            this.richTextContentControl165.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl166
            // 
            this.richTextContentControl166.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl167
            // 
            this.richTextContentControl167.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl168
            // 
            this.richTextContentControl168.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl169
            // 
            this.richTextContentControl169.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl170
            // 
            this.richTextContentControl170.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl171
            // 
            this.richTextContentControl171.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl172
            // 
            this.richTextContentControl172.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl173
            // 
            this.richTextContentControl173.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl174
            // 
            this.richTextContentControl174.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl175
            // 
            this.richTextContentControl175.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl176
            // 
            this.richTextContentControl176.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl177
            // 
            this.richTextContentControl177.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl178
            // 
            this.richTextContentControl178.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl179
            // 
            this.richTextContentControl179.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl180
            // 
            this.richTextContentControl180.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl181
            // 
            this.richTextContentControl181.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl182
            // 
            this.richTextContentControl182.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl183
            // 
            this.richTextContentControl183.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl184
            // 
            this.richTextContentControl184.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl185
            // 
            this.richTextContentControl185.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl186
            // 
            this.richTextContentControl186.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl187
            // 
            this.richTextContentControl187.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl188
            // 
            this.richTextContentControl188.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl189
            // 
            this.richTextContentControl189.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl190
            // 
            this.richTextContentControl190.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl191
            // 
            this.richTextContentControl191.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl192
            // 
            this.richTextContentControl192.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl193
            // 
            this.richTextContentControl193.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl194
            // 
            this.richTextContentControl194.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl195
            // 
            this.richTextContentControl195.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl196
            // 
            this.richTextContentControl196.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl197
            // 
            this.richTextContentControl197.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl198
            // 
            this.richTextContentControl198.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl199
            // 
            this.richTextContentControl199.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl200
            // 
            this.richTextContentControl200.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl201
            // 
            this.richTextContentControl201.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl202
            // 
            this.richTextContentControl202.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl203
            // 
            this.richTextContentControl203.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl204
            // 
            this.richTextContentControl204.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl205
            // 
            this.richTextContentControl205.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl206
            // 
            this.richTextContentControl206.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl207
            // 
            this.richTextContentControl207.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl208
            // 
            this.richTextContentControl208.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl209
            // 
            this.richTextContentControl209.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl210
            // 
            this.richTextContentControl210.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl211
            // 
            this.richTextContentControl211.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl212
            // 
            this.richTextContentControl212.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl213
            // 
            this.richTextContentControl213.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl214
            // 
            this.richTextContentControl214.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl215
            // 
            this.richTextContentControl215.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl216
            // 
            this.richTextContentControl216.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl217
            // 
            this.richTextContentControl217.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl218
            // 
            this.richTextContentControl218.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl219
            // 
            this.richTextContentControl219.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl220
            // 
            this.richTextContentControl220.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl221
            // 
            this.richTextContentControl221.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl222
            // 
            this.richTextContentControl222.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl223
            // 
            this.richTextContentControl223.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl224
            // 
            this.richTextContentControl224.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl225
            // 
            this.richTextContentControl225.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl226
            // 
            this.richTextContentControl226.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl227
            // 
            this.richTextContentControl227.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl228
            // 
            this.richTextContentControl228.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl229
            // 
            this.richTextContentControl229.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl230
            // 
            this.richTextContentControl230.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl231
            // 
            this.richTextContentControl231.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl232
            // 
            this.richTextContentControl232.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl233
            // 
            this.richTextContentControl233.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl234
            // 
            this.richTextContentControl234.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl235
            // 
            this.richTextContentControl235.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl236
            // 
            this.richTextContentControl236.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl237
            // 
            this.richTextContentControl237.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl238
            // 
            this.richTextContentControl238.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl239
            // 
            this.richTextContentControl239.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl240
            // 
            this.richTextContentControl240.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl241
            // 
            this.richTextContentControl241.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl242
            // 
            this.richTextContentControl242.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl243
            // 
            this.richTextContentControl243.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl244
            // 
            this.richTextContentControl244.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl245
            // 
            this.richTextContentControl245.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl246
            // 
            this.richTextContentControl246.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl247
            // 
            this.richTextContentControl247.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl248
            // 
            this.richTextContentControl248.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl249
            // 
            this.richTextContentControl249.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl250
            // 
            this.richTextContentControl250.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl251
            // 
            this.richTextContentControl251.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl252
            // 
            this.richTextContentControl252.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl253
            // 
            this.richTextContentControl253.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl254
            // 
            this.richTextContentControl254.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl255
            // 
            this.richTextContentControl255.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl256
            // 
            this.richTextContentControl256.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl257
            // 
            this.richTextContentControl257.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl258
            // 
            this.richTextContentControl258.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl259
            // 
            this.richTextContentControl259.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl260
            // 
            this.richTextContentControl260.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl261
            // 
            this.richTextContentControl261.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl262
            // 
            this.richTextContentControl262.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl263
            // 
            this.richTextContentControl263.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl264
            // 
            this.richTextContentControl264.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl265
            // 
            this.richTextContentControl265.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl266
            // 
            this.richTextContentControl266.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl267
            // 
            this.richTextContentControl267.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl268
            // 
            this.richTextContentControl268.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl269
            // 
            this.richTextContentControl269.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl270
            // 
            this.richTextContentControl270.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // richTextContentControl271
            // 
            this.richTextContentControl271.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // ThisDocument
            // 
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void OnShutdown() {
            this.richTextContentControl271.Dispose();
            this.richTextContentControl270.Dispose();
            this.richTextContentControl269.Dispose();
            this.richTextContentControl268.Dispose();
            this.richTextContentControl267.Dispose();
            this.richTextContentControl266.Dispose();
            this.richTextContentControl265.Dispose();
            this.richTextContentControl264.Dispose();
            this.richTextContentControl263.Dispose();
            this.richTextContentControl262.Dispose();
            this.richTextContentControl261.Dispose();
            this.richTextContentControl260.Dispose();
            this.richTextContentControl259.Dispose();
            this.richTextContentControl258.Dispose();
            this.richTextContentControl257.Dispose();
            this.richTextContentControl256.Dispose();
            this.richTextContentControl255.Dispose();
            this.richTextContentControl254.Dispose();
            this.richTextContentControl253.Dispose();
            this.richTextContentControl252.Dispose();
            this.richTextContentControl251.Dispose();
            this.richTextContentControl250.Dispose();
            this.richTextContentControl249.Dispose();
            this.richTextContentControl248.Dispose();
            this.richTextContentControl247.Dispose();
            this.richTextContentControl246.Dispose();
            this.richTextContentControl245.Dispose();
            this.richTextContentControl244.Dispose();
            this.richTextContentControl243.Dispose();
            this.richTextContentControl242.Dispose();
            this.richTextContentControl241.Dispose();
            this.richTextContentControl240.Dispose();
            this.richTextContentControl239.Dispose();
            this.richTextContentControl238.Dispose();
            this.richTextContentControl237.Dispose();
            this.richTextContentControl236.Dispose();
            this.richTextContentControl235.Dispose();
            this.richTextContentControl234.Dispose();
            this.richTextContentControl233.Dispose();
            this.richTextContentControl232.Dispose();
            this.richTextContentControl231.Dispose();
            this.richTextContentControl230.Dispose();
            this.richTextContentControl229.Dispose();
            this.richTextContentControl228.Dispose();
            this.richTextContentControl227.Dispose();
            this.richTextContentControl226.Dispose();
            this.richTextContentControl225.Dispose();
            this.richTextContentControl224.Dispose();
            this.richTextContentControl223.Dispose();
            this.richTextContentControl222.Dispose();
            this.richTextContentControl221.Dispose();
            this.richTextContentControl220.Dispose();
            this.richTextContentControl219.Dispose();
            this.richTextContentControl218.Dispose();
            this.richTextContentControl217.Dispose();
            this.richTextContentControl216.Dispose();
            this.richTextContentControl215.Dispose();
            this.richTextContentControl214.Dispose();
            this.richTextContentControl213.Dispose();
            this.richTextContentControl212.Dispose();
            this.richTextContentControl211.Dispose();
            this.richTextContentControl210.Dispose();
            this.richTextContentControl209.Dispose();
            this.richTextContentControl208.Dispose();
            this.richTextContentControl207.Dispose();
            this.richTextContentControl206.Dispose();
            this.richTextContentControl205.Dispose();
            this.richTextContentControl204.Dispose();
            this.richTextContentControl203.Dispose();
            this.richTextContentControl202.Dispose();
            this.richTextContentControl201.Dispose();
            this.richTextContentControl200.Dispose();
            this.richTextContentControl199.Dispose();
            this.richTextContentControl198.Dispose();
            this.richTextContentControl197.Dispose();
            this.richTextContentControl196.Dispose();
            this.richTextContentControl195.Dispose();
            this.richTextContentControl194.Dispose();
            this.richTextContentControl193.Dispose();
            this.richTextContentControl192.Dispose();
            this.richTextContentControl191.Dispose();
            this.richTextContentControl190.Dispose();
            this.richTextContentControl189.Dispose();
            this.richTextContentControl188.Dispose();
            this.richTextContentControl187.Dispose();
            this.richTextContentControl186.Dispose();
            this.richTextContentControl185.Dispose();
            this.richTextContentControl184.Dispose();
            this.richTextContentControl183.Dispose();
            this.richTextContentControl182.Dispose();
            this.richTextContentControl181.Dispose();
            this.richTextContentControl180.Dispose();
            this.richTextContentControl179.Dispose();
            this.richTextContentControl178.Dispose();
            this.richTextContentControl177.Dispose();
            this.richTextContentControl176.Dispose();
            this.richTextContentControl175.Dispose();
            this.richTextContentControl174.Dispose();
            this.richTextContentControl173.Dispose();
            this.richTextContentControl172.Dispose();
            this.richTextContentControl171.Dispose();
            this.richTextContentControl170.Dispose();
            this.richTextContentControl169.Dispose();
            this.richTextContentControl168.Dispose();
            this.richTextContentControl167.Dispose();
            this.richTextContentControl166.Dispose();
            this.richTextContentControl165.Dispose();
            this.richTextContentControl164.Dispose();
            this.richTextContentControl163.Dispose();
            this.richTextContentControl162.Dispose();
            this.richTextContentControl161.Dispose();
            this.richTextContentControl160.Dispose();
            this.richTextContentControl159.Dispose();
            this.richTextContentControl158.Dispose();
            this.richTextContentControl157.Dispose();
            this.richTextContentControl156.Dispose();
            this.richTextContentControl155.Dispose();
            this.richTextContentControl154.Dispose();
            this.richTextContentControl153.Dispose();
            this.richTextContentControl147.Dispose();
            this.richTextContentControl146.Dispose();
            this.richTextContentControl1.Dispose();
            this.Tender_Submission_Programme.Dispose();
            this.Tender_Format.Dispose();
            this.Tender_Evaluation_Procedure.Dispose();
            this.Supplier_Selection_Method.Dispose();
            this.Pricing_Options.Dispose();
            this.Personnel_Schedule.Dispose();
            this.Non_Price_Attributes.Dispose();
            this.Interactive_Tender_Process.Dispose();
            this.Geotechnical_Testing_Schedule.Dispose();
            this.Contract_Pricing.Dispose();
            this.Contract_Details.Dispose();
            this.Additional_Services_Schedule.Dispose();
            this.richTextContentControl145.Dispose();
            this.richTextContentControl144.Dispose();
            this.ActionsPane.Dispose();
            base.OnShutdown();
        }
    }
    
    /// 
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
    internal sealed partial class Globals {
        
        /// 
        private Globals() {
        }
        
        private static ThisDocument _ThisDocument;
        
        private static global::Microsoft.Office.Tools.Word.Factory _factory;
        
        private static ThisRibbonCollection _ThisRibbonCollection;
        
        internal static ThisDocument ThisDocument {
            get {
                return _ThisDocument;
            }
            set {
                if ((_ThisDocument == null)) {
                    _ThisDocument = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
        
        internal static global::Microsoft.Office.Tools.Word.Factory Factory {
            get {
                return _factory;
            }
            set {
                if ((_factory == null)) {
                    _factory = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
        
        internal static ThisRibbonCollection Ribbons {
            get {
                if ((_ThisRibbonCollection == null)) {
                    _ThisRibbonCollection = new ThisRibbonCollection(_factory.GetRibbonFactory());
                }
                return _ThisRibbonCollection;
            }
        }
    }
    
    /// 
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "12.0.0.0")]
    internal sealed partial class ThisRibbonCollection : Microsoft.Office.Tools.Ribbon.RibbonCollectionBase {
        
        /// 
        internal ThisRibbonCollection(global::Microsoft.Office.Tools.Ribbon.RibbonFactory factory) : 
                base(factory) {
        }
    }
}
